const timelineData = [
  {
    imageSrc: 'https://picsum.photos/seed/tl-birth/700/900',
    position: { x: -0.5, y: 0 },
    backgroundColor: '#F5EDE0',
    blob1Color: '#E8D0A8',
    blob2Color: '#C9A77C',
    accentColor: '#C9A77C',
    year: '1977',
    lifePhase: 'Birth',
    caption: 'Born in Johannesburg',
    description: 'The beginning of a remarkable life',
  },
  {
    imageSrc: 'https://picsum.photos/seed/tl-school/700/900',
    position: { x: 0.65, y: 0 },
    backgroundColor: '#EEF3EE',
    blob1Color: '#9DB096',
    blob2Color: '#B8CAB0',
    accentColor: '#6B8064',
    year: '1990s',
    lifePhase: 'Youth',
    caption: 'Coming of age',
    description: 'School years, friendships, and first dreams',
  },
  {
    imageSrc: 'https://picsum.photos/seed/tl-career/700/900',
    position: { x: -0.75, y: 0 },
    backgroundColor: '#FAF0E0',
    blob1Color: '#C9A77C',
    blob2Color: '#D4A05A',
    accentColor: '#B8904A',
    year: '2000s',
    lifePhase: 'Beginnings',
    caption: 'Finding his path',
    description: 'Career, purpose, and a world of possibility',
  },
  {
    imageSrc: 'https://picsum.photos/seed/tl-wedding/700/900',
    position: { x: 0.8, y: 0 },
    backgroundColor: '#EEF3EE',
    blob1Color: '#9DB096',
    blob2Color: '#6B8064',
    accentColor: '#6B8064',
    year: '2004',
    lifePhase: 'Love',
    caption: 'Wedding day',
    description: 'A new chapter, shared with the one he loved',
  },
  {
    imageSrc: 'https://picsum.photos/seed/tl-family/700/900',
    position: { x: -0.6, y: 0 },
    backgroundColor: '#F2EBE0',
    blob1Color: '#D4B898',
    blob2Color: '#9DB096',
    accentColor: '#9DB096',
    year: '2010s',
    lifePhase: 'Family',
    caption: 'A full life at home',
    description: 'Sunday braais, a stoep full of laughter',
  },
  {
    imageSrc: 'https://picsum.photos/seed/tl-legacy/700/900',
    position: { x: 0.5, y: 0 },
    backgroundColor: '#E8E0D8',
    blob1Color: '#7A7060',
    blob2Color: '#9DB096',
    accentColor: '#7A7060',
    year: '2025',
    lifePhase: 'Legacy',
    caption: 'A life well lived',
    description: 'Remembered, cherished, and never forgotten',
  },
]

export { timelineData }
